[[patch]]
file = "D:/ycdivfx/UnityDev/20191129_facebook_camtools/FisheyeLut/Assets/LensTools/Editor/LensToolsEditor.cs"
[[patch.change]]
search = 'BUILD DATE: (\d{4}/\d{2}/\d{2} \d{2}:\d{2})'
replace = "BUILD DATE: @date"
[[patch.change]]
search = 'GIT HASH: (\w+)'
replace = "GIT HASH: @gitrev"